default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mysql2_dev

test:
  <<: *default
  database: mysql2_test

production:
  <<: *default
  database: mysql2_pro
  socket: /var/lib/mysql/mysql.sock
